Added object.hpp and object.cpp
segmentation-chaos/parabolic_battle pull request #1
Opened 2019-09-26 13:26 UTC by vitor-de-oliveira

- Created the files object.hpp and object.hpp.
- Added the object.cpp dependency on makefile
- Created a tests folder which, for now, contains a main file for testing the object files and a data file with the exit of the before mentioned test

2019-09-27 01:52 UTC, pedroishida commented on include/system.hpp
> +#include "canvas.hpp"
Deixar em ordem alfabética.

2019-09-27 01:57 UTC, vitor-de-oliveira reviewed
Fiz as mudanças sugeridas pelo Pedro

2019-09-27 01:57 UTC, vitor-de-oliveira commented on include/system.hpp
> +#include "canvas.hpp"
Done.

2019-09-27 01:57 UTC, pedroishida commented on src/main.cpp
> +#include <iostream>
Como o `main` não utiliza funções do `<stdio.h>` ou do `<iostream>`, as bibliotecas devem ser retiradas e colocadas nos códigos onde são utilizadas.

Para programas em C++ as bibliotecas em C a serem utilizadas não possuem `.h` e começam com a letra `c`. No caso, `<stdio.h>` seria substituído por `<cstdio>`.

2019-09-27 01:58 UTC, pedroishida commented on src/main.cpp
> +using namespace std;
O namespace `std` não é utilizado no `main`. Pode ser retirado.

2019-09-27 01:58 UTC, vitor-de-oliveira commented on src/main.cpp
> +#include <iostream>
Nós estávamos utilizando essas bibliotecas nos testes que fizemos e esquecemos de tirar.
Usamos as bibliotecas do C e não do C++ por praticidade mesmo.

2019-09-27 02:01 UTC, vitor-de-oliveira commented on src/main.cpp
> +using namespace std;
Beleza. Ficou dos testes também.

2019-09-27 02:02 UTC, pedroishida commented on tests/bullet_trajectory.dat
> +1.106066 0.995749
Como este arquivo de dados é gerado pelo programa, não devemos guardá-lo no versionamento do código.

2019-09-27 02:06 UTC, vitor-de-oliveira commented on tests/bullet_trajectory.dat
> +1.106066 0.995749
Beleza.

2019-09-27 02:07 UTC, pedroishida commented on tests/main_for_testing_object.cpp
> +#include <stdio.h>
Usar `<cstdio>` no lugar de `<stdio.h>` e colocar em ordem alfabética.

2019-09-27 02:07 UTC, pedroishida requested changes
Remover o binário _parabolic_batle_.

2019-09-27 14:01 UTC, vitor-de-oliveira commented on tests/main_for_testing_object.cpp
> +#include <stdio.h>
Done.

2019-10-07 14:50 UTC, matheuslazarotto approved these changes
Dadas as correções do Pedro, Approved!

2019-10-17 20:39 UTC, pedroishida approved these changes

2019-10-17 20:39 UTC, pedroishida commented on src/object.cpp
> +#include <math.h>
Esse `#include` deve ir no _object.hpp_.

2019-10-17 22:27 UTC, vitor-de-oliveira commented on src/object.cpp
> +#include <math.h>
Done.

2019-10-17 22:27 UTC, merged