Moving bullet
segmentation-chaos/parabolic_battle pull request #3
Opened 2019-10-11 21:44 UTC by pedroishida

2019-10-11 21:48 UTC, pedroishida commented
Ainda farei algumas mudanças, mas já criei a Pull Request.

Como o _merge_ não será feito no **dev**, não é necessário aprovação. Mas fiz um pedido de _review_ do @vitor-de-oliveira.

2019-10-11 22:09 UTC, pedroishida commented on include/object.hpp
> -        int shoot(double init_vel, double init_angle, int orientation);
@vitor-de-oliveira 
Eu tirei os nomes das variáveis desse _header_ para ficar igual aos outros. Mas se achar melhor coloco nos outros.

2019-10-14 14:51 UTC, vitor-de-oliveira commented on include/object.hpp
> -        int shoot(double init_vel, double init_angle, int orientation);
Beleza. Pode ficar sem os nomes mesmo.

2019-10-14 14:55 UTC, vitor-de-oliveira approved these changes
Mudanças revisadas.

2019-10-14 15:01 UTC, vitor-de-oliveira requested changes
Precisa mudar a dependência da função shoot no "system.cpp".

2019-10-14 15:01 UTC, vitor-de-oliveira commented on src/system.cpp
> +			0
Depois que eu aprovei as mudanças, eu rodei o programa na minha máquina e percebi que essa linha está errada.

2019-10-15 01:20 UTC, pedroishida commented on src/system.cpp
> +			0
Bem lembrado. Fiz as mudanças.

2019-10-15 12:57 UTC, vitor-de-oliveira approved these changes

2019-10-15 13:10 UTC, merged